### ISSUE TITLE
Error: Gravebot node index.js

### ISSUE THREAD

**Issue by crater0** [Gravestorm/Gravebot#126]
Hello,

Trying to start gravebot on my linux machine results in this error:

```
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'start' ]
2 info using npm@2.14.18
3 info using node@v0.10.25
4 verbose node symlink /usr/bin/node
5 verbose run-script [ 'prestart', 'start', 'poststart' ]
6 info prestart gravebot@2.0.0
7 info start gravebot@2.0.0
8 verbose unsafe-perm in lifecycle true
9 info gravebot@2.0.0 Failed to exec start script
10 verbose stack Error: gravebot@2.0.0 start: `node index.js`
10 verbose stack Exit status 8
10 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
10 verbose stack     at EventEmitter.emit (events.js:98:17)
10 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
10 verbose stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
10 verbose stack     at maybeClose (child_process.js:743:16)
10 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:810:5)
11 verbose pkgid gravebot@2.0.0
12 verbose cwd /home/bot/Gravebot
13 error Linux 4.2.0-27-generic
14 error argv "node" "/usr/local/bin/npm" "start"
15 error node v0.10.25
16 error npm  v2.14.18
17 error code ELIFECYCLE
18 error gravebot@2.0.0 start: `node index.js`
18 error Exit status 8
19 error Failed at the gravebot@2.0.0 start script 'node index.js'.
19 error This is most likely a problem with the gravebot package,
19 error not with npm itself.
19 error Tell the author that this fails on your system:
19 error     node index.js
19 error You can get information on how to open an issue for this project with:
19 error     npm bugs gravebot
19 error Or if that isn't available, you can get their info via:
19 error
19 error     npm owner ls gravebot
19 error There is likely additional logging output above.
20 verbose exit [ 1, true ]
```

Please excuse me if I missed something stupid, but I cannot figure out what is causing this error.

Thanks!

**Comment by dustinblackman** [comment]
Your version of node is highly outdated. `v0.10.25. Upgrade to Node 4.2.6 and npm 3.7.1.

**Comment by crater0** [comment]
Hmm, the error still seems to be occuring

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@3.7.1
3 info using node@v4.2.6
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle gravebot@2.0.0~prestart: gravebot@2.0.0
6 silly lifecycle gravebot@2.0.0~prestart: no script for prestart, continuing
7 info lifecycle gravebot@2.0.0~start: gravebot@2.0.0
8 verbose lifecycle gravebot@2.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle gravebot@2.0.0~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/home/bot/Gravebot/node_modules/.bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
10 verbose lifecycle gravebot@2.0.0~start: CWD: /home/bot/Gravebot
11 silly lifecycle gravebot@2.0.0~start: Args: [ '-c', 'node index.js' ]
12 silly lifecycle gravebot@2.0.0~start: Returned: code: 1  signal: null
13 info lifecycle gravebot@2.0.0~start: Failed to exec start script
14 verbose stack Error: gravebot@2.0.0 start: `node index.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:239:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:821:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid gravebot@2.0.0
16 verbose cwd /home/bot/Gravebot
17 error Linux 4.2.0-27-generic
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
19 error node v4.2.6
20 error npm  v3.7.1
21 error code ELIFECYCLE
22 error gravebot@2.0.0 start: `node index.js`
22 error Exit status 1
23 error Failed at the gravebot@2.0.0 start script 'node index.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the gravebot package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node index.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs gravebot
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls gravebot
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by dustinblackman** [comment]
Try running the application without NPM and see if we can get a better error log. `node index.js`

**Comment by crater0** [comment]
```
[2016-02-07 23:47:55] Booting...
module.js:328
    throw err;
    ^

Error: Cannot find module './dist'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/bot/Gravebot/index.js:9:3)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
```
i tried reinstalling all dependencies and rerunning `npm install`, no change.

**Comment by dustinblackman** [comment]
Ah. Your `npm install` failed to run `npm run postinstall`. It's a permission problem npm has on linux, haven't quite figured out why. Run `npm run postinstall` and you'll be good to go.

**Comment by crater0** [comment]
Running `npm run postinstall` causes this error:

```
npm ERR! Linux 4.2.0-27-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "postinstall"
npm ERR! node v4.2.6
npm ERR! npm  v3.7.1
npm ERR! code ELIFECYCLE
npm ERR! gravebot@2.0.0 postinstall: `npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gravebot@2.0.0 postinstall script 'npm run build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the gravebot package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs gravebot
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls gravebot
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/bot/Gravebot/npm-debug.log
```
then, running `npm run build` manually results in this:

```
npm ERR! Linux 4.2.0-27-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v4.2.6
npm ERR! npm  v3.7.1
npm ERR! code ELIFECYCLE
npm ERR! gravebot@2.0.0 build: `rm -rf ./dist && babel src --out-dir dist --copy-files`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gravebot@2.0.0 build script 'rm -rf ./dist && babel src --out-dir dist --copy-files'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the gravebot package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     rm -rf ./dist && babel src --out-dir dist --copy-files
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs gravebot
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls gravebot
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/bot/Gravebot/npm-debug.log
```

Trying to run `rm -rf ./dist && babel src --out-dir dist --copy-files` then causes:

```
babel: cannot write output format!
Open Babel 2.3.2 -- Sep  6 2015 -- 08:21:10
Usage: babel [-i<input-type>] <name> [-o<output-type>] <name>
Try  -H option for more information.
```

Not sure if I'm missing something like running the wrong version of babel, but I cannot seem to figure this problem either.

**Comment by crater0** [comment]
Ok, figured out the problem. 

`babel-runtime` was failing to install, manually running `npm install babel-runtime`, deleting `node_modules` and rerunning `npm install` fixed all my problems.
