### ISSUE TITLE
Help me with this error log

### ISSUE THREAD

**Issue by xSnowyAngel** [Gravestorm/Gravebot#138]
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@2.14.12
3 info using node@v4.3.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart gravebot@2.0.0
6 info start gravebot@2.0.0
7 verbose unsafe-perm in lifecycle true
8 info gravebot@2.0.0 Failed to exec start script
9 verbose stack Error: gravebot@2.0.0 start: `node index.js`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:214:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:821:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid gravebot@2.0.0
11 verbose cwd C:\Users\admin\Desktop\Games\Grave Bot\Gravebot-master
12 error Windows_NT 10.0.10586
13 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
14 error node v4.3.0
15 error npm  v2.14.12
16 error code ELIFECYCLE
17 error gravebot@2.0.0 start: `node index.js`
17 error Exit status 1
18 error Failed at the gravebot@2.0.0 start script 'node index.js'.
18 error This is most likely a problem with the gravebot package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     node index.js
18 error You can get their info via:
18 error     npm owner ls gravebot
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
```

did i do something wrong?
P.S im new to this

**Comment by dustinblackman** [comment]
You missed the error when running `npm install` that said `postinstall` didn't fire. Run `npm run build` and you'll be fine.

**Comment by xSnowyAngel** [comment]
when i run ```npm run build ``` it says

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@2.14.12
3 info using node@v4.3.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info prebuild gravebot@2.0.0
6 info build gravebot@2.0.0
7 verbose unsafe-perm in lifecycle true
8 info gravebot@2.0.0 Failed to exec build script
9 verbose stack Error: gravebot@2.0.0 build: `rm -rf ./dist && babel src --out-dir dist --copy-files`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:214:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:821:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid gravebot@2.0.0
11 verbose cwd C:\Users\admin\Desktop\Games\Grave Bot\Gravebot-master
12 error Windows_NT 10.0.10586
13 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
14 error node v4.3.0
15 error npm  v2.14.12
16 error code ELIFECYCLE
17 error gravebot@2.0.0 build: `rm -rf ./dist && babel src --out-dir dist --copy-files`
17 error Exit status 1
18 error Failed at the gravebot@2.0.0 build script 'rm -rf ./dist && babel src --out-dir dist --copy-files'.
18 error This is most likely a problem with the gravebot package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     rm -rf ./dist && babel src --out-dir dist --copy-files
18 error You can get their info via:
18 error     npm owner ls gravebot
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
```

P.S im new to this

**Comment by insuusvenerati** [comment]
You're gonna want to run this on Linux. Not windows. Good luck.

**Comment by xSnowyAngel** [comment]
ohh, thanks
